name: "Common Pentaho Maven Settings file"
description: "Common Pentaho Maven Settings file"

inputs:
  changed_modules:
    description: "Comma-separated list of modules that have been edited"
  test_scenario_json:
    description: "For PDI plugin integration tests, path to the json file containing test scenarios for each plugin"

outputs:
  settings-file-path:
    description: "Maven settings file path"
    value: ${{ steps.settings-file.outputs.path }}

runs:
  using: "composite"
  steps:

    - name: Checkout code
      if: ${{ env.run_plugin_integration_tests == '' }}
      uses: actions/checkout@v4

    - name: Return settings.xml
      id: settings-file
      shell: sh
      run: |
        file_path="$GITHUB_ACTION_PATH/settings.xml"
        
        echo "path=${file_path}" >> $GITHUB_OUTPUT

    # PDI plugin integration test section
    - name: Configure vm.max_map_count required by Elasticsearch
      if: ${{ env.run_plugin_integration_tests }}
      shell: bash
      run: |
        echo "vm.max_map_count=262144" >> /etc/sysctl.conf

    - name: Checkout reusable workflow source repo
      uses: actions/checkout@v4
      with:
        repository: pentaho/actions-common
        path: actions-common
        ref: stable
        clean: false

    - name: Run plugin integration tests
      if: ${{ env.run_plugin_integration_tests && inputs.test_scenario_json && inputs.changed_modules }}
      uses: lumada-common-services/gh-composite-actions@stable
      env:
        cmd_type: INTEGRATION_TEST
        int_test_report_path: '**/target/failsafe-reports/TEST*.xml'
        int_test_reporter: 'java-junit'
        int_test_fail_on_error: 'true'
      with:
        command: |
          actions-common/.github/scripts/sh/run-pdi-plugin-integration-tests.sh \
          "${{ inputs.test_scenario_json }}" \
          "${{ inputs.changed_modules  }}"
