name: Pentaho pull request workflow
on:
  workflow_call:
    inputs:
      slack_channels:
        type: string
        required: true
        description: "Slack channel(s) to send notifications to."
      arti_host:
        required: false
        type: string
        default: https://repo.orl.eng.hitachivantara.com
        description: "Artifactory's Host name"
      sonar_project_key:
        required: true
        type: string
        description: "Sonar's project identifier key"
      sonar_url:
        required: false
        type: string
        description: "Sonar's URL"
        default: https://sonar.orl.eng.hitachivantara.com
      test_scenario_json:
        required: false
        type: string
        description: "For PDI plugin integration tests, path to the json file containing test scenarios for each plugin"
        default: "./.github/plugin_integration_test_scenarios.json"
      base_version:
        type: string
        required: true
        description: "Base version to be taken in consideration for dependencies"

env:

  BASE_VERSION: "${{ inputs.base_version }}"

  SONAR_PROJECT_KEY: ${{ inputs.sonar_project_key }}
  SONAR_HOST_URL: ${{ inputs.sonar_url }}
  SONAR_LOGIN: ${{secrets.WINGMAN_SONAR_TOKEN}}

  ARTIFACTORY_HOST: ${{ inputs.arti_host }}
  ARTIFACTORY_BASE_URL: ${ARTIFACTORY_HOST}/artifactory

  RESOLVE_REPO_MIRROR: ${ARTIFACTORY_BASE_URL}/pnt-mvn

  NEXUS_DEPLOY_USER: ${{ secrets.ARTIFACTORY_USER }}
  NEXUS_DEPLOY_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}

  PUBLIC_RELEASE_REPO_URL: ${ARTIFACTORY_BASE_URL}/pntpub-mvn-dev-orl
  PRIVATE_RELEASE_REPO: pntprv-mvn-dev-orl
  PRIVATE_RELEASE_REPO_URL: ${ARTIFACTORY_BASE_URL}/${PRIVATE_RELEASE_REPO}

  PUBLIC_SNAPSHOT_REPO_URL: ${ARTIFACTORY_BASE_URL}/pntpub-mvn-snapshot-orl
  PRIVATE_SNAPSHOT_REPO: pntprv-mvn-snapshot-orl
  PRIVATE_SNAPSHOT_REPO_URL: ${ARTIFACTORY_BASE_URL}/${PRIVATE_SNAPSHOT_REPO}

  DOCKER_PULL_HOST: pnt-docker.repo.orl.eng.hitachivantara.com/
  DOCKER_PUBLIC_PUSH_HOST: pntpub-docker-dev-orl.repo.orl.eng.hitachivantara.com
  DOCKER_PRIVATE_PUSH_HOST: pntprv-docker-dev-orl.repo.orl.eng.hitachivantara.com

  SLACK_CHANNEL: "${{ inputs.slack_channels }}"

jobs:

  setup-maven-settings:
    name: Setup Maven settings

    runs-on: [ k8s ]

    container:
      image: cicd-oci-release-orl.repo.orl.eng.hitachivantara.com/pentaho/actions-common:20231205.49
      volumes:
        - /home/runner/caches/pentaho/.m2:/root/.m2

    steps:

      - name: Retrieve settings file
        id: common-maven
        uses: pentaho/actions-common@1.0.0

      - name: Copy settings.xml to .m2 directory
        shell: sh
        run: |
          cp "${{ steps.common-maven.outputs.settings-file-path }}" /root/.m2
    

  common-job:
    name: Common Checks
    needs: setup-maven-settings
    runs-on: [ k8s ]

    container:
      image: cicd-oci-release-orl.repo.orl.eng.hitachivantara.com/pentaho/actions-common:20231205.49
      volumes:
        - /home/runner/caches/pentaho/.m2:/root/.m2

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine which changes occurred
        id: change_detection
        uses: hv-actions/change-detection-builder@HNC-522

      # - name: Build the project for changed modules only
      #   uses: lumada-common-services/gh-composite-actions@HNC-510
      #   with:
      #     command: mvn clean install -pl "${{ steps.change_detection.outputs.changed_modules }}" -DskipTests -amd
      #   env:
      #     cmd_type: BUILD

      # - name: Trigger Citadel scan
      #   id: Citadel
      #   uses: lumada-common-services/gh-composite-actions@stable
      #   env:
      #     TRIGGER_CITADEL_SCAN: true
      #     CITADEL_URL: 'https://citadel.wal.eng.hitachivantara.com/citadel' 
      #     SECRETS_CONTEXT: ${{ toJson(secrets) }}
      #     VARS_CONTEXT: ${{ toJson(vars) }}

      # - name: Run unit-tests
      #   uses: lumada-common-services/gh-composite-actions@stable
      #   with:
      #     command: |
      #       mvn verify -pl "${{ steps.change_detection.outputs.changed_modules }}" -B -Daudit -amd && \
      #       cd azure-datalake2-vfs && \
      #       ls -alR
      #   env:
      #     cmd_type: UNIT_TEST
      #     reporter: 'java-junit'
      #     test_report_path: '**/target/surefire-reports/*.xml'
      #     fail-on-empty: true

      - name: FrogBot
        uses: lumada-common-services/gh-composite-actions@stable
        env:
          JF_URL: https://hitachi.jfrog.io/
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ github.token }}
             
      # # TODO when done testing, uncomment other steps, set correct actions-common version (master?)
      # - name: Run PDI plugin integration tests
      #   uses: pentaho/actions-common@BACKLOG-39097-III
      #   with:
      #     changed_modules: "${{ steps.change_detection.outputs.changed_modules }}"
      #     test_scenario_json: "${{ inputs.test_scenario_json }}"
      #   env:
      #     run_plugin_integration_tests: true

#
#      - name: Sonarqube scan
#        uses: lumada-common-services/gh-composite-actions@1.7.1
#        env:
#          sonar_utility: sonar-scanner
#          sonar_commands: '("-Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{env.SONAR_HOST_URL}} -Dsonar.login=${{env.SONAR_LOGIN}} -Dsonar.pullrequest.key=${{github.event.number}} -Dsonar.pullrequest.branch=${{github.event.pull_request.head.ref}} -Dsonar.pullrequest.base=${{github.event.pull_request.base.ref}}")'
#
      # - name: Report notifications
      #   if: always()
      #   uses: lumada-common-services/gh-composite-actions@HNC-502
      #   env:
      #     Slack_Token: ${{ secrets.SLACK_TOKEN }}
      #     Slack_Channel: ${{ env.SLACK_CHANNEL }}
      #     report: true
