name: Pentaho pull request workflow
on:
  workflow_call:
    inputs:
      slack_channels:
        type: string
        required: true
        description: "Slack channel(s) to send notifications to."
      arti_host:
        required: false
        type: string
        default: https://one.hitachivantara.com
        description: "Artifactory's Host name"
      sonar_project_key:
        required: true
        type: string
        description: "Sonar's project identifier key"
      sonar_url:
        required: false
        type: string
        description: "Sonar's URL"
        default: https://sonar.orl.eng.hitachivantara.com
      test_scenario_json:
        required: false
        type: string
        description: "For PDI plugin integration tests, path to the json file containing test scenarios for each plugin"
      base_version:
        type: string
        required: false
        description: "Base version to be taken in consideration for dependencies"
      modules_to_always_build_in_addition_to_those_with_changes:
        type: string
        required: false
        description: "List of modules to build in addition to those that have changes."
      additional_mvn_directives:
        required: false
        type: string
        description: "Extra additional directives for the Maven command"
        default: ""


env:
  SONAR_PROJECT_KEY: ${{ inputs.sonar_project_key }}
  SONAR_HOST_URL: ${{ inputs.sonar_url }}
  SONAR_LOGIN: ${{secrets.WINGMAN_SONAR_TOKEN}}

  ARTIFACTORY_HOST: ${{ inputs.arti_host }}
  ARTIFACTORY_BASE_URL: ${ARTIFACTORY_HOST}/artifactory

  RESOLVE_REPO_MIRROR: ${ARTIFACTORY_BASE_URL}/maven

  NEXUS_DEPLOY_USER: ${{ secrets.PENTAHO_CICD_ONE_USER }}
  NEXUS_DEPLOY_PASSWORD: ${{ secrets.PENTAHO_CICD_ONE_KEY }}

  PUBLIC_RELEASE_REPO_URL: ${ARTIFACTORY_BASE_URL}/pntpub-maven-dev
  PRIVATE_RELEASE_REPO: pntprv-maven-dev
  PRIVATE_RELEASE_REPO_URL: ${ARTIFACTORY_BASE_URL}/${PRIVATE_RELEASE_REPO}

  PUBLIC_SNAPSHOT_REPO_URL: ${ARTIFACTORY_BASE_URL}/pntpub-maven-snapshot
  PRIVATE_SNAPSHOT_REPO: pntprv-maven-snapshot
  PRIVATE_SNAPSHOT_REPO_URL: ${ARTIFACTORY_BASE_URL}/${PRIVATE_SNAPSHOT_REPO}

  DOCKER_PULL_HOST: one.hitachivantara.com/docker/
  DOCKER_PUBLIC_PUSH_HOST: one.hitachivantara.com/pntpub-docker-dev/
  DOCKER_PRIVATE_PUSH_HOST: one.hitachivantara.com/pntprv-docker-dev/

  SLACK_CHANNEL: "${{ inputs.slack_channels }}"

jobs:

  setup-maven-settings:
    name: Setup Maven settings

    runs-on: [ k8s ]

    container:
      image: one.hitachivantara.com/devops-docker-release/pentaho/actions-common:20240305.137
      credentials:
        username: ${{ secrets.PENTAHO_CICD_ONE_USER }}
        password: ${{ secrets.PENTAHO_CICD_ONE_KEY }}
      volumes:
        - /home/runner/caches/pentaho/.m2:/root/.m2

    steps:

      - name: Retrieve settings file
        id: common-maven
        uses: pentaho/actions-common@stable

      - name: Copy settings.xml to .m2 directory
        shell: sh
        run: |
          cp "${{ steps.common-maven.outputs.settings-file-path }}" /root/.m2
    

  common-job:
    name: Common Checks
    needs: setup-maven-settings
    runs-on: [ k8s ]

    container:
      image: one.hitachivantara.com/devops-docker-release/pentaho/actions-common:20240305.137
      credentials:
        username: ${{ secrets.PENTAHO_CICD_ONE_USER }}
        password: ${{ secrets.PENTAHO_CICD_ONE_KEY }}
      volumes:
        - /home/runner/caches/pentaho/.m2:/root/.m2

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update cmd_type as per the mvn_directives
        if: env.SET_CMD_TYPE == null
        run: |
          if [[ -n "${{ inputs.additional_mvn_directives }}" && "${{ inputs.additional_mvn_directives }}" == *"-DrunITs"* ]]; then
            echo "SET_CMD_TYPE=BUILD,UNIT_TEST,INTEGRATION_TEST" >> $GITHUB_ENV
          else
            echo "SET_CMD_TYPE=BUILD,UNIT_TEST" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Determine which changes occurred
        id: change_detection
        uses: hv-actions/change-detection-builder@stable

      - name: Build & Run tests
        uses: lumada-common-services/gh-composite-actions@stable
        with:
          command: |
            mvn clean verify -DskipTests=false -Daudit -amd \
            -pl "${{ format('{0},{1}', inputs.modules_to_always_build_in_addition_to_those_with_changes, steps.change_detection.outputs.changed_modules) }}" \
            ${{ inputs.additional_mvn_directives }}
        env:
          cmd_type: ${{ env.SET_CMD_TYPE }}
          unit_test_reporter: 'java-junit'
          unit_test_fail_on_error: 'true'
          unit_test_report_path: '**/target/surefire-reports/*.xml'
          int_test_reporter: 'java-junit'
          int_test_fail_on_error: 'true'
          int_test_report_path: '**/target/failsafe-reports/TEST*.xml'

      - name: Run PDI plugin integration tests
        uses: pentaho/actions-common@stable
        if: ${{ inputs.test_scenario_json }}
        with:
          changed_modules: "${{ steps.change_detection.outputs.changed_modules }}"
          test_scenario_json: "${{ inputs.test_scenario_json }}"
        env:
          run_plugin_integration_tests: true
          BASE_VERSION: "${{ inputs.base_version }}"

      - name: Sonarqube scan
        uses: lumada-common-services/gh-composite-actions@stable
        env:
          sonar_utility: sonar-scanner
          sonar_commands: '("-Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{env.SONAR_HOST_URL}} -Dsonar.login=${{env.SONAR_LOGIN}} -Dsonar.pullrequest.key=${{github.event.number}} -Dsonar.pullrequest.branch=${{github.event.pull_request.head.ref}} -Dsonar.pullrequest.base=${{github.event.pull_request.base.ref}}")'

      - name: FrogBot
        uses: lumada-common-services/gh-composite-actions@stable
        env:
          JF_URL: https://one.hitachivantara.com
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.HV_ACTIONS_GIT_TOKEN }}

      - name: Report notifications
        if: always()
        uses: lumada-common-services/gh-composite-actions@stable
        env:
          Slack_Token: ${{ secrets.SLACK_TOKEN }}
          Slack_Channel: ${{ env.SLACK_CHANNEL }}
          report: true