
name: Called by Curl

on:
  workflow_dispatch:
    inputs:
      build_cmd:
        description: 'My build command'
      test_cmd:
        description: 'My test command'
      release_version:
        required: true
        description: 'Version to be set and built'
      build_number:
        required: true
        description: 'Orchestration Build number'

        
jobs:

  deal-with-inputs:
    runs-on: [self-hosted]
    steps:

      - run: echo "actions-minion"

      - name: Output Inputs
          run: echo "${{ toJSON(github.event.inputs) }}"